- name: copy access_key to target
  local_action:
    copy:
      src: "{{ k3s_backup_etcd_s3_access_key }}"
      dest: /data/tmp/access_key

- name: copy secret_key to target
  local_action:
    copy:
      src: "{{ k3s_backup_etcd_s3_secret_key }}"
      dest: /data/tmp/secret_key